config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shopstop.urls", namespace="shop")),
    #include users app
    path("users/", include("users.urls", namespace= "users")),
    path("orders/",include("orders.urls", namespace="orders"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.contrib import admin
from django.urls import path
from home.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home-page"),
]

shopstop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('',views.home, name="home"),
    path('shop/', views.shop, name= 'shop'),
    #product page
    path('detail/<item_id>', views.product_detail, name = 'prod-detail'),
    #add item
    path('add-item/', views.add_item, name = 'add-item'),
    path('business/register/', views.business_register, name='business_register'),
    path('menu/manage/', views.menu_management, name='menu_management'),
    path('service/manage/', views.service_management, name='service_management'),
    path('manage_business/<business_id>', views.business_management, name = 'management'),
    path('about/', views.about, name='about'),
    path('business-profile/', views.business_profile, name = 'business-profile'),
    #business form
    path('business_form/', views.create_business, name = 'create_business')
    
]

shopstop/models.py
from django.db import models
from users.models import CustomUser

#main app models
class Business(models.Model):   #List of businesses registered
    owner = models.OneToOneField(CustomUser, on_delete=models.CASCADE,  blank=True, null = True)
    name = models.CharField(max_length=255)
    contact_details = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    description = models.CharField(max_length = 500)
    logo = models.ImageField(upload_to='logos/', null=True, blank=True)
    videos = models.FileField(upload_to='videos/', blank = True) 
    photos = models.ImageField(upload_to='photos/', blank = True)


    class Meta:
        verbose_name_plural = 'Businesses'

    def __str__(self):
        return f'{self.name}'

class Item(models.Model):     #items on the menu list with their corresponding prices
    business = models.ForeignKey(Business, on_delete=models.CASCADE, null=True)
    item_name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.CharField(default="Product description",max_length=1000)
    date_added = models.DateTimeField(auto_now_add = True)
    availability = models.BooleanField(default=True)
    photos = models.ImageField(upload_to='photos/', blank = True)
    def __str__(self):
        return f'{ self.item_name}'
    
    def imageURL(self):
        try:
            url = self.photos.url
        except:
            url = ''
        return url
    
    
class Service(models.Model):  #services provided by certain businesses
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    service_name = models.CharField(max_length=255)
    price = models.IntegerField()
    picture = models.ImageField(upload_to='services/', blank = True)
    date_added = models.DateTimeField(auto_now_add = True)
    availability = models.BooleanField(default=True)

    def __str__(self):
        return f' {self.service_name}'
        
    
class Business_photos_videos(models.Model):  #Businesses can upload their photos and videos
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    photos = models.ImageField(upload_to='photos/', blank = True) 
    videos = models.FileField(upload_to='videos/', blank = True) 

    def __str__(self):
        return f'{self.business}'  
    
class Order(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete = models.SET_NULL, blank=True, null = True)
    date_ordered = models.DateTimeField(auto_now_add = True)
    complete = models.BooleanField(default = False, null=True, blank = True)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self) -> str:
        return str(self.id)
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Item,on_delete=models.SET_NULL, blank = True, null= True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank = True, null = True)
    quantity = models.PositiveIntegerField(default=0, null=True,blank = True)
    date_added = models.DateTimeField(auto_now_add = True)

    @property
    def get_total(self):
        total = self.product.price *self.quantity
        return total

shopstop/forms.py
from django import forms
from django.forms import ModelForm
from .models import Item, Business

#add item form
class  ItemModelForm(ModelForm):
    class Meta:
        model = Item
        fields=('item_name','price','photos',)


class BusinessForm(ModelForm):
    class Meta:
        model = Business
        fields = ['name', 'contact_details', 'location', 'description', 'logo', 'photos', 'videos']
        widgets = {
            'description': forms.Textarea(attrs={ 'rows': 5}),  
        }        

shopstop/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .models import *
from .forms import ItemModelForm, BusinessForm

#views to manage the main app
def business_management(request, business_id):
    business = Business.objects.get(id = business_id)
    services = business.service_set.order_by("date_added")
    items = business.item_set.order_by("date_added")
    context = {"services":services, "items":items, "business" : business}

    return render(request,'shop/business-admin.html', context)

def add_item(request):
    business = Business.objects.get(owner = request.user)
    if request.method == 'POST': # If the form has been submitted...
        form = ItemModelForm(request.POST, request.FILES) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            item_name = form.cleaned_data['item_name']
            price = form.cleaned_data['price']
            photos = form.cleaned_data['photos']

            item = Item.objects.create(
                business =  business,
                item_name = item_name,
                price = price,
                photos = photos 
            )
            item.save()
            return redirect('shop:shop')
    else: 
        form = ItemModelForm() # An unbound form
    
    return render(request, 'shop/product/add-item.html', {'form': form})


def create_business(request):
    if request.method == 'POST':
        form = BusinessForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('business-profile/')  
    else:
        form = BusinessForm()
    return render(request, 'shop/businesses/business_form.html', {'form': form})    



def shop(request):
        items = Item.objects.all()
        services = Service.objects.all()
        context = {'items':items,'services':services}
        return render(request, "shop/home.html", context)

def product_detail(request, item_id):
     item = Item.objects.get(id = item_id)
     return render(request, 'shop/product/product_detail.html', {'item':item})

def home(request):
    return render(request, 'shop/index.html')

def about(request):
    return render(request, 'shop/about_us.html')

def service_management(request):
    template = loader.get_template('services.html')
    return HttpResponse(template.render())

def menu_management(request):
    template = loader.get_template('shop/menu.html')
    context = {'list':[1,2,3,4]}
    return HttpResponse(template.render())

def business_register(request):
    template = loader.get_template( 'register.html')
    return HttpResponse(template.render() )

def business_profile(request):
    return render(request,'shop/business-profile-page.html')

shopstop/templates/shop/about_us.html
{% extends 'shop/base2.html' %}

  <style>
   

    section {
      padding: 20px;
    }
    .footer {
      background-color:navy;
      color: #fff;
      padding: 10px 0;
      text-align: center;
      margin: 20px 0;
    }
    .testimonial p {
      font-style: italic;
      color: #666;
    }
    #testimonials {
      background-color: #f9f9f9;
      text-align: center;
    }
    #contact {
        color: #fff;
        text-align: center;
    }
  
    #contact ul {
        list-style-type: none;
    }
    .content-box {
      background-color:aquamarine;
      border-radius: 20px;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
      padding: 20px;
      margin: 20px;
    }
    .header{
      background-color: #033;
      color: #fff;
      padding: 10px 0;
      text-align: center;
      margin: 20px 0;
    }
  </style>
  {% block content %}
  <br><br><br><br>
  <div class = "about">
    <div class="content-box">
      <h2>About Us</h2>
      <p>Welcome to Shopstop!</p>
      <p> We specialize in providing high-quality products at affordable prices and excellent customer service. Our mission is to make online shopping easy and enjoyable for our customers.</p>
      <p>With a wide range of products to choose from and excellent customer service, we strive to exceed your expectations with every purchase.</p>
    </div>
      <h2>Some of the businesses we partner with</h2>
      <ul>
        <li>Shoe companys</li>
        <li>Cake baking</li>
        <li>Car accessories</li>
        <li>Boutiques</li>
      </ul>

    <section id="testimonials">
      <h2>Customer Testimonials</h2>
      <div class="testimonial">
        <p>"Shopstop has greatly improved our business operations. Highly recommended!" - John Doe, CEO</p>
      </div>
    </section>
  </div>
  {%endblock%}

shopstop/templates/shop/base.html
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>ShopStop galaxy</title>
  <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <link rel="stylesheet" href="{% static 'css/nav-style.css'%}">
  <script>
    var user = '{{request.user}}'

    function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');
  </script>
  

</head>
<body>
    
    
    {% block base_content %}
    {% endblock %}
    
    <script  src="{% static 'js/script.js' %}"></script>
    <script  src="{% static 'js/nav.js' %}"></script>
    <script src="{% static 'js/cart.js' %}"></script>
    <script src='https://unpkg.co/gsap@3/dist/gsap.min.js'></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

shopstop/templates/shop/base2.html
{% extends 'shop/base.html' %}

{# base page for all pages that need a footer, navbar #}
{% block base_content %}
  {% include 'shop/base/navbar.html' %}
  {% block content %}
  {% endblock %}
{% endblock %}

shopstop/templates/shop/home.html
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html>
  <head>
    <title>Stop Shop</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link rel="stylesheet" type="text/css" href="{% static 'css/new_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav-style.css' %}">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@300;400;500&family=Lato:wght@300;400;700&display=swap" rel="stylesheet">
    <!-- script ================================================== -->
    <script>
      var user = '{{request.user}}'

      function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
              const cookie = cookies[i].trim();
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
      }
      const csrftoken = getCookie('csrftoken');
    </script>
    
  </head>
  <body data-bs-spy="scroll" data-bs-theme="dark" data-bs-target="#navbar" data-bs-root-margin="0px 0px -40%" data-bs-smooth-scroll="true" tabindex="0">
    
    <header class="site-header position-fixed ">
      {% include 'shop/base/shopbar.html' %}
    </header>
    <br><br><br><br>
    <div class="display-4 text-light">
      Welcome to Stop Shop!
    </div>
    <section id="billboard">
      
      
      <div class="container">
        <div class="d-flex display-3 text-light align-items-center justify-content-center">
          Products
        </div>
        
        <div class="row d-flex flex-wrap justify-content-center align-items-center mt-5">
          
          {% for item in items %}
          <div class="col pb-3 ">
          <div class="card2">
            <a href="{% url 'shop:prod-detail' item.id %}"><img class="card2-img" src="{{item.photos.url}}" alt="null"></a>
            <div class="card2-info">
              <p class="text-title">{{item.item_name}} </p>
              <p class="text-body">Product description and details</p>
            </div>
            <div class="card2-footer">
            <span class="text-title"><strong>${{item.price}}</strong></span>
            <button class="update-cart" data-product="{{item.id}}" data-action="add" style="border:none ; background-color: transparent;">
              <div class="card2-button " data-product="{{item.id}}" data-action="add">
                <i class="fa-solid fa-cart-shopping"></i>
              </div>
            </button>
          </div></div></div>
          {% endfor %}
        </div>
      </div>
      
      
    </section>
    <section id="company-services" class="padding-large">
      <div class="container">
        <div class="d-flex display-3 text-light align-items-center justify-content-center">
          Services
        </div>
        
        <div class="d-flex flex-row justify-content-evenly">
        {% for service in services %}
        <div class="col pb-3 ">
          <div class="card2">
            <a href=""><img class="card2-img" src="{{service.picture.url}}" alt="{{service.service_name}}"></a>
            <div class="card2-info">
              <p class="text-title">{{service.service_name}} </p>
              <p class="text-body">Product description and details</p>
            </div>
            <div class="card2-footer">
            <span class="text-title "><strong>${{service.price}}</strong></span>
            <div class="card2-button update-cart" >
              <i class="fa-solid fa-cart-shopping"></i>
            </div>
          </div></div></div>
        {% endfor  %}
        </div>
      </div>
    </section>
    
    
    
    <script>
      var user = '{{request.user}}'
    </script>
    <script  src="{% static 'js/script.js' %}"></script>
    <script  src="{% static 'js/nav.js' %}"></script>
    <script  src="{% static 'js/cart.js' %}"></script>
    <script src='https://unpkg.co/gsap@3/dist/gsap.min.js'></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

shopstop/templates/shop/index.html
{% extends 'shop/base2.html' %}
{% block content %}
<div class="experience"></div>
{%endblock%}