config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shopstop.urls", namespace="shop")),
    #include users app
    path("users/", include("users.urls", namespace= "users")),
    path("orders/",include("orders.urls", namespace="orders"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.contrib import admin
from django.urls import path
from home.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home-page"),
]

orders/urls.py
from django.urls import path
from . import views
app_name = "orders"

urlpatterns=[
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name="checkout"),
    path('update_item/', views.update_item, name='update_item')

]

shopstop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('',views.home, name="home"),
    path('shop/', views.shop, name= 'shop'),
    #product page
    path('detail/<item_id>', views.product_detail, name = 'prod-detail'),
    #add item
    path('add-item/', views.add_item, name = 'add-item'),
    path('business/register/', views.business_register, name='business_register'),
    path('menu/manage/', views.menu_management, name='menu_management'),
    path('service/manage/', views.service_management, name='service_management'),
    path('manage_business/<business_id>', views.business_management, name = 'management'),
    path('about/', views.about, name='about'),
    path('business-profile/', views.business_profile, name = 'business-profile'),
    #business form
    path('business_form/', views.create_business, name = 'create_business')
    
]

orders/models.py
from django.db import models

# Create your models here.

shopstop/models.py
from django.db import models
from users.models import CustomUser

#main app models
class Business(models.Model):   #List of businesses registered
    owner = models.OneToOneField(CustomUser, on_delete=models.CASCADE,  blank=True, null = True)
    name = models.CharField(max_length=255)
    contact_details = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    description = models.CharField(max_length = 500)
    logo = models.ImageField(upload_to='logos/', null=True, blank=True)
    videos = models.FileField(upload_to='videos/', blank = True) 
    photos = models.ImageField(upload_to='photos/', blank = True)


    class Meta:
        verbose_name_plural = 'Businesses'

    def __str__(self):
        return f'{self.name}'

class Item(models.Model):     #items on the menu list with their corresponding prices
    business = models.ForeignKey(Business, on_delete=models.CASCADE, null=True)
    item_name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.CharField(default="Product description",max_length=1000)
    date_added = models.DateTimeField(auto_now_add = True)
    availability = models.BooleanField(default=True)
    photos = models.ImageField(upload_to='photos/', blank = True)
    def __str__(self):
        return f'{ self.item_name}'
    
    def imageURL(self):
        try:
            url = self.photos.url
        except:
            url = ''
        return url
    
    
class Service(models.Model):  #services provided by certain businesses
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    service_name = models.CharField(max_length=255)
    price = models.IntegerField()
    picture = models.ImageField(upload_to='services/', blank = True)
    date_added = models.DateTimeField(auto_now_add = True)
    availability = models.BooleanField(default=True)

    def __str__(self):
        return f' {self.service_name}'
        
    
class Business_photos_videos(models.Model):  #Businesses can upload their photos and videos
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    photos = models.ImageField(upload_to='photos/', blank = True) 
    videos = models.FileField(upload_to='videos/', blank = True) 

    def __str__(self):
        return f'{self.business}'  
    
class Order(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete = models.SET_NULL, blank=True, null = True)
    date_ordered = models.DateTimeField(auto_now_add = True)
    complete = models.BooleanField(default = False, null=True, blank = True)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self) -> str:
        return str(self.id)
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Item,on_delete=models.SET_NULL, blank = True, null= True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank = True, null = True)
    quantity = models.PositiveIntegerField(default=0, null=True,blank = True)
    date_added = models.DateTimeField(auto_now_add = True)

    @property
    def get_total(self):
        total = self.product.price *self.quantity
        return total

shopstop/forms.py
from django import forms
from django.forms import ModelForm
from .models import Item, Business

#add item form
class  ItemModelForm(ModelForm):
    class Meta:
        model = Item
        fields=('item_name','price','photos',)


class BusinessForm(ModelForm):
    class Meta:
        model = Business
        fields = ['name', 'contact_details', 'location', 'description', 'logo', 'photos', 'videos']
        widgets = {
            'description': forms.Textarea(attrs={ 'rows': 5}),  
        }        

orders/views.py
from django.shortcuts import render
from shopstop.models import Order, OrderItem, Item
from django.http import JsonResponse
import json


#views to create cart items
def cart(request):
    if request.user.is_authenticated:
        order, created = Order.objects.get_or_create(customer=request.user, complete = False)
        items = order.orderitem_set.all()
    else:    
        items=[]
        order ={'get_cart_total':0,'get_cart_items':0}
    context = {'items':items, 
               'order':order}
    return render(request,"shop/cart/cart.html", context)

def checkout(request):
    if request.user.is_authenticated:
        order, created = Order.objects.get_or_create(customer=request.user, complete = False)
        items = order.orderitem_set.all()
    else:    
        items=[]
        order ={'get_cart_total':0,'get_cart_items':0}
    context = {'items':items, 
               'order':order}
    return render(request,"shop/cart/checkout.html", context)

def update_item(request):
    data = json.loads(request.body)
    productId = data['product_id']
    action = data['action']

    customer = request.user
    product = Item.objects.get(id=productId)
    order,created = Order.objects.get_or_create(customer=customer, complete=False)
    order_item,created = OrderItem.objects.get_or_create(order=order, product=product)
    if action == "add":
        order_item.quantity = (order_item.quantity+1)
    elif action == "remove":
        order_item.quantity = (order_item.quantity-1)

    order_item.save()

    if order_item.quantity <= 0:
        order_item.delete()

    return JsonResponse(action + ' complete', safe=False)

shopstop/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .models import *
from .forms import ItemModelForm, BusinessForm

#views to manage the main app
def business_management(request, business_id):
    business = Business.objects.get(id = business_id)
    services = business.service_set.order_by("date_added")
    items = business.item_set.order_by("date_added")
    context = {"services":services, "items":items, "business" : business}

    return render(request,'shop/business-admin.html', context)

def add_item(request):
    business = Business.objects.get(owner = request.user)
    if request.method == 'POST': # If the form has been submitted...
        form = ItemModelForm(request.POST, request.FILES) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            item_name = form.cleaned_data['item_name']
            price = form.cleaned_data['price']
            photos = form.cleaned_data['photos']

            item = Item.objects.create(
                business =  business,
                item_name = item_name,
                price = price,
                photos = photos 
            )
            item.save()
            return redirect('shop:shop')
    else: 
        form = ItemModelForm() # An unbound form
    
    return render(request, 'shop/product/add-item.html', {'form': form})


def create_business(request):
    if request.method == 'POST':
        form = BusinessForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('business-profile/')  
    else:
        form = BusinessForm()
    return render(request, 'shop/businesses/business_form.html', {'form': form})    



def shop(request):
        items = Item.objects.all()
        services = Service.objects.all()
        context = {'items':items,'services':services}
        return render(request, "shop/home.html", context)

def product_detail(request, item_id):
     item = Item.objects.get(id = item_id)
     return render(request, 'shop/product/product_detail.html', {'item':item})

def home(request):
    return render(request, 'shop/index.html')

def about(request):
    return render(request, 'shop/about_us.html')

def service_management(request):
    template = loader.get_template('services.html')
    return HttpResponse(template.render())

def menu_management(request):
    template = loader.get_template('shop/menu.html')
    context = {'list':[1,2,3,4]}
    return HttpResponse(template.render())

def business_register(request):
    template = loader.get_template( 'register.html')
    return HttpResponse(template.render() )

def business_profile(request):
    return render(request,'shop/business-profile-page.html')

shopstop/templates/shop/cart/cart.html
{% extends 'shop/base2.html' %}
{% load bootstrap5 %}
{% bootstrap_css%}
{% bootstrap_javascript%}
{% block content %}

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <hr>
<div class="container bg-light rounded">
  <table id="cart" class="table table-hover table-condensed">
    <thead>
      <tr>
        <th style="width:50%">Product</th>
        <th style="width:10%">Price</th>
        <th style="width:8%">Quantity</th>
        <th style="width:22%" class="text-center">Subtotal</th>
        <th style="width:10%"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        {% for item in items %}
        <td data-th="Product">
            
          <div class="row p-4">
            <div class="col-sm-2 hidden-xs"><img src="{{item.product.photos.url}}" style="height: 100px; width: 100px;" alt="..." class="img-responsive" /></div>
            <div class="col-sm-10">
              <h4 class="nomargin">{{item.product.item_name}}</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
          </div>
        </td>
        <td data-th="Price">${{item.product.price}}</td>
        <td data-th="Quantity">
          {{item.quantity}}
        </td>
        <td data-th="Subtotal" class="text-center">${{item.get_total}}</td>
        <td class="actions" data-th="">
          <button data-product="{{item.product.id}}" data-action="add" class="btn btn-info btn-sm update-cart"><i class="fa fa-plus"></i></button>
          <button data-product="{{item.product.id}}" class="btn btn-danger btn-sm update-cart" data-action="remove"><i class="fa fa-trash-o"></i></button>
        </td>
      </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr class="visible-xs">
        <td class="text-center"><strong>Total items {{order.get_cart_items}}</strong></td>
      </tr>
      <tr>
        <td><a href="{% url 'shop:shop' %}" class="py-3" style="color: black; text-decoration: none; background-color: gray;"><button   class="fbtn btn-dark text-light"><i class="fa fa-angle-left"></i> Continue Shopping</button></a></td>
        <td colspan="2" class="hidden-xs"></td>
        <td class="hidden-xs text-center"><strong>Total $ {{order.get_cart_total}}</strong></td>
        <td><a href="{% url 'orders:checkout' %}" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
      </tr>
    </tfoot>
  </table>
</div>
</div>
{% endblock %}

shopstop/templates/shop/cart/checkout.html
{% extends 'shop/base2.html' %}
{% load static %}
{% load bootstrap5 %}
{% block content %}
<div class="container text-light">
    <h1>Order Summary <br>  Items:{{order.get_cart_items}} Total:&dollar;{{order.get_cart_total}} <a href="{% url 'orders:cart' %}" style="text-decoration: none; float: right;"><button class="add-cart fbtn">Back to cart</button></a></h1> 
    <hr />
    
    <!-- The method get_absolute_url() returns the URL to access a particular object -->
    {% for item in items %}
    <div class="container-glass d-flex flex-col justify-content-end mx-auto" style="transform: scale(0.7);">
        <div class="box w-70 ">
            
          <span class="title text-align-right">{{ item.product.item_name }}</span><br>
          <div class="glass-img" style="height: 100px; width: 100px;">
            
            <img class="img-fluid img-thumbnail h-100" src="{{ item.product.photos.url }}" alt="{{ item.product.item_name }}" > 
          </div>
          <div>
            <div></div>
            

          </div>
          
          <div class=""><strong><b>Total:</b> ${{ item.get_total }}</strong>
        Quantity: {{item.quantity}}
        </div>
            
            
        </div>
      </div>
      
    </div> 
    {% endfor %}
    
{% endblock %}
  
 

shopstop/templates/shop/cart/order.html
<h1>Your Order</h1>

<table id="checkout-cart" class="shopping-cart">
    <thead>
        <tr>
            <th scope="col">Item</th>
            <th scope="col">Qty</th>
            <th scope="col">Price</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

<div id="pricing">
    <p id="shipping">
        <strong>Shipping</strong>: <span id="sshipping"></span>
    </p>

    <p id="sub-total">
        <strong>Total</strong>: <span id="stotal"></span>
    </p>
</div>

<div id="user-details">
    <h2>Your Data</h2>
        <div id="user-details-content"></div>
</div>

<form id="paypal-form" action="" method="post">
    <input type="hidden" name="cmd" value="_cart" />
    <input type="hidden" name="upload" value="1" />
    <input type="hidden" name="business" value="" />

    <input type="hidden" name="currency_code" value="" />
    <input type="submit" id="paypal-btn" class="btn" value="Pay with PayPal" />
</form>