config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shopstop.urls", namespace="shop")),
    #include users app
    path("users/", include("users.urls", namespace= "users")),
    path("orders/",include("orders.urls", namespace="orders"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.contrib import admin
from django.urls import path
from home.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home-page"),
]

orders/urls.py
from django.urls import path
from . import views
app_name = "orders"

urlpatterns=[
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name="checkout"),
    path('update_item/', views.update_item, name='update_item')

]

shopstop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('',views.home, name="home"),
    path('shop/', views.shop, name= 'shop'),
    #product page
    path('detail/<item_id>', views.product_detail, name = 'prod-detail'),
    #add item
    path('add-item/', views.add_item, name = 'add-item'),
    path('business/register/', views.business_register, name='business_register'),
    path('menu/manage/', views.menu_management, name='menu_management'),
    path('service/manage/', views.service_management, name='service_management'),
    path('manage_business/<business_id>', views.business_management, name = 'management'),
    path('about/', views.about, name='about'),
    path('business-profile/', views.business_profile, name = 'business-profile'),
    #business form
    path('business_form/', views.create_business, name = 'create_business')
    
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns= [
    # 用户登录
    path('login/', views.user_login, name='user_login'),
    #signup
    path('signup/',views.signup,name='signup'),
    #log out
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.profileform, name='profile')
]

shopstop/models.py
from django.db import models
from users.models import CustomUser

#main app models
class Business(models.Model):   #List of businesses registered
    owner = models.OneToOneField(CustomUser, on_delete=models.CASCADE,  blank=True, null = True)
    name = models.CharField(max_length=255)
    contact_details = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    description = models.CharField(max_length = 500)
    logo = models.ImageField(upload_to='logos/', null=True, blank=True)
    videos = models.FileField(upload_to='videos/', blank = True) 
    photos = models.ImageField(upload_to='photos/', blank = True)


    class Meta:
        verbose_name_plural = 'Businesses'

    def __str__(self):
        return f'{self.name}'

class Item(models.Model):     #items on the menu list with their corresponding prices
    business = models.ForeignKey(Business, on_delete=models.CASCADE, null=True)
    item_name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.CharField(default="Product description",max_length=1000)
    date_added = models.DateTimeField(auto_now_add = True)
    availability = models.BooleanField(default=True)
    photos = models.ImageField(upload_to='photos/', blank = True)
    def __str__(self):
        return f'{ self.item_name}'
    
    def imageURL(self):
        try:
            url = self.photos.url
        except:
            url = ''
        return url
    
    
class Service(models.Model):  #services provided by certain businesses
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    service_name = models.CharField(max_length=255)
    price = models.IntegerField()
    picture = models.ImageField(upload_to='services/', blank = True)
    date_added = models.DateTimeField(auto_now_add = True)
    availability = models.BooleanField(default=True)

    def __str__(self):
        return f' {self.service_name}'
        
    
class Business_photos_videos(models.Model):  #Businesses can upload their photos and videos
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    photos = models.ImageField(upload_to='photos/', blank = True) 
    videos = models.FileField(upload_to='videos/', blank = True) 

    def __str__(self):
        return f'{self.business}'  
    
class Order(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete = models.SET_NULL, blank=True, null = True)
    date_ordered = models.DateTimeField(auto_now_add = True)
    complete = models.BooleanField(default = False, null=True, blank = True)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self) -> str:
        return str(self.id)
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Item,on_delete=models.SET_NULL, blank = True, null= True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank = True, null = True)
    quantity = models.PositiveIntegerField(default=0, null=True,blank = True)
    date_added = models.DateTimeField(auto_now_add = True)

    @property
    def get_total(self):
        total = self.product.price *self.quantity
        return total

shopstop/forms.py
from django import forms
from django.forms import ModelForm
from .models import Item, Business

#add item form
class  ItemModelForm(ModelForm):
    class Meta:
        model = Item
        fields=('item_name','price','photos',)


class BusinessForm(ModelForm):
    class Meta:
        model = Business
        fields = ['name', 'contact_details', 'location', 'description', 'logo', 'photos', 'videos']
        widgets = {
            'description': forms.Textarea(attrs={ 'rows': 5}),  
        }        

shopstop/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .models import *
from .forms import ItemModelForm, BusinessForm

#views to manage the main app
def business_management(request, business_id):
    business = Business.objects.get(id = business_id)
    services = business.service_set.order_by("date_added")
    items = business.item_set.order_by("date_added")
    context = {"services":services, "items":items, "business" : business}

    return render(request,'shop/business-admin.html', context)

def add_item(request):
    business = Business.objects.get(owner = request.user)
    if request.method == 'POST': # If the form has been submitted...
        form = ItemModelForm(request.POST, request.FILES) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            item_name = form.cleaned_data['item_name']
            price = form.cleaned_data['price']
            photos = form.cleaned_data['photos']

            item = Item.objects.create(
                business =  business,
                item_name = item_name,
                price = price,
                photos = photos 
            )
            item.save()
            return redirect('shop:shop')
    else: 
        form = ItemModelForm() # An unbound form
    
    return render(request, 'shop/product/add-item.html', {'form': form})


def create_business(request):
    if request.method == 'POST':
        form = BusinessForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('business-profile/')  
    else:
        form = BusinessForm()
    return render(request, 'shop/businesses/business_form.html', {'form': form})    



def shop(request):
        items = Item.objects.all()
        services = Service.objects.all()
        context = {'items':items,'services':services}
        return render(request, "shop/home.html", context)

def product_detail(request, item_id):
     item = Item.objects.get(id = item_id)
     return render(request, 'shop/product/product_detail.html', {'item':item})

def home(request):
    return render(request, 'shop/index.html')

def about(request):
    return render(request, 'shop/about_us.html')

def service_management(request):
    template = loader.get_template('services.html')
    return HttpResponse(template.render())

def menu_management(request):
    template = loader.get_template('shop/menu.html')
    context = {'list':[1,2,3,4]}
    return HttpResponse(template.render())

def business_register(request):
    template = loader.get_template( 'register.html')
    return HttpResponse(template.render() )

def business_profile(request):
    return render(request,'shop/business-profile-page.html')

shopstop/templates/shop/base/footer.html
<footer>
    <div id="txt2">
        <span>Shop </span>
    </div>
    <div id="txt">
        <div class="best-sellers-column">
            <p>Best Sellers</p>
            <ul>
                <li><a href="Cake baking.html">Cake baking</a></li>
                <li><a href="Graphic design.html">Graphic design</a></li>
            </ul>
        </div>
        
        <div class="new-releases-column">
            <p>New releases</p>
            <ul>
                <li><a href="Shoe company.html">Shoe company</a></li>
                <li><a href="Digital marketing.html">Digital marketing</a></li>
            </ul>
        </div>
    
        <div class="today's-deals-column">
            <p>Today's deals</p>
            <ul>
                <li><a href="Car washer.html">Car washer</a></li>
                <li><a href="Cleaning service.html">Cleaning service</a></li>
            </ul>
        </div>
        
    </div>
</footer>

shopstop/templates/shop/base/navbar.html
<div class="navbar">
  <nav >
    <ul style="font-family: 'Courier New', Courier, monospace; font-size: 25px;" >
      <li class="active">
        <a href="{% url 'shop:home' %}">Home</a>
      </li>
      <li>
        <a href="{% url 'shop:shop' %}">Shop</a>
      </li>
      {% if user.is_authenticated %}
      <li>
        <a href="{% url 'users:logout' %}">Logout</a>
      </li>
      <li>
        <a href="{% url 'shop:create_business'%}">Create Business</a>
      </li>
      {% else %}
      <li>
        <a href="{% url 'users:user_login' %}">Login</a>
      </li>
      <li>
        <a href="{% url 'users:signup' %}">Sign up</a>
      </li>
      {% endif %}

    </ul>
  </nav>  
</div>

shopstop/templates/shop/base/shopbar.html
<div class="nav_container">
  <nav>
    <ul>
      <li class="active">
        <button ><a href="{% url 'shop:home' %}">Home</a></button>
      </li>
      <li>
        <button><a href="#billboard">Products</a></button>
      </li>
      <li>
        <button ><a href="#company-services">Services</a></button>
      </li>
      <a class="pt-1" href="{% url 'orders:cart' %}"><i class="fa-solid fa-cart-shopping"></i></a>
    </ul>
  

  </nav>
  
  
      
        <a class="navbar-brand" href="{% url 'shop:shop' %}">
          <span class="title">STOP SHOP</span>
        </a>
            
    
</div>